### ISSUE TITLE
Error when wanting to install - node/npm/ruby

### ISSUE THREAD

**Issue by robben-ar** [filidorwiese/multeor#4]
Hi!
I love the development you have made.
I am trying to carry out the installation but I am having problems and errors.
When executing npm install I returned several errors of versions with node v0.8.28, v0.9.9, v0.12.18, v4.2.2.

With what versions of software node, npm, ruby, apache should I perform the installation?

Thank you.-

**Comment by robben-ar** [comment]
I managed to move forward with the help of a friend ..
With version node version 6.17.1 I get up well and did not break the score.
Now I do not see the image of the top of the score.
I just need to generate facebook the token for users to be on leaderboard.


Regards.-

**Comment by filidorwiese** [comment]
Hi! Sorry for the no-reply. Out of nostalgia I've dockerized this repo for easier deployment and local developing. Which might be of use to you :rocket:
